# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: modul-symptom
canonical: https://www.medizininformatik-initiative.de/fhir/ext/modul-symptom
title: "MII IG Symptom"
name: MII_IG_Symptom
status: active
version: 2024.0.0-ballot
packageId: de.medizininformatikinitiative.kerndatensatz.symptom
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# menu:
#   Home: index.html
#   Artifacts: artifacts.html
dependencies:
  de.medizininformatikinitiative.kerndatensatz.meta: 
    uri: de.medizininformatikinitiative.kerndatensatz.meta
    version: 1.0.3
  de.basisprofil.r4:
    uri: de.basisprofil.r4
    version: 1.4.0
